<?php
/**
 * Plugin Name: WP Central Worker Plugin
 * Description: Lightweight WordPress worker plugin for Central WordPress Management System. Supports secure HMAC-SHA256 authentication, asynchronous backups (to S3 or local disk), automated updates, and custom plugin vault sideloading.
 * Version: 1.2.3
 * Author: WP Central Team
 * License: GPL2
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

/**
 * Security & Authentication Helper Class
 */
class WPCentral_Security {
    private static $secret_key_option_name = 'wp_central_secret_key';

    public static function get_secret_key() {
        $secret = get_option(self::$secret_key_option_name);
        if (!$secret) {
            $secret = defined('WP_CENTRAL_SECRET_KEY') ? WP_CENTRAL_SECRET_KEY : 'default_secret_key_12345';
        }
        return $secret;
    }

    public static function set_secret_key($key) {
        update_option(self::$secret_key_option_name, $key);
    }

    /**
     * Reconstruct and verify the HMAC-SHA256 signature
     */
    public static function verify_request(WP_REST_Request $request) {
        $signature = $request->get_header('X-Signature');
        $timestamp = intval($request->get_header('X-Timestamp'));

        if (empty($signature) || empty($timestamp)) {
            return new WP_Error(
                'rest_forbidden',
                __('Missing signature or timestamp headers.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 1. Prevent Replay: Check clock drift (max 5 minutes)
        if (abs(time() - $timestamp) > 300) {
            return new WP_Error(
                'rest_forbidden',
                __('Request expired. Clock drift too high.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 2. Prevent Replay: Verify signature hasn't been used before
        $transient_key = 'wp_central_sig_' . md5($signature);
        if (get_transient($transient_key)) {
            return new WP_Error(
                'rest_forbidden',
                __('Replay attack detected. Signature already used.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 3. Verify Signature
        $raw_body = $request->get_body();
        $data_to_sign = $timestamp . '.' . $raw_body;
        $secret_key = self::get_secret_key();
        $expected_signature = hash_hmac('sha256', $data_to_sign, $secret_key);

        if (!hash_equals($expected_signature, $signature)) {
            return new WP_Error(
                'rest_forbidden',
                __('Invalid signature.', 'wp-central'),
                array('status' => 403)
            );
        }

        // Store the signature in transient to prevent replay for the duration of its validity (5 minutes)
        set_transient($transient_key, true, 300);
        return true;
    }

    /**
     * Sign requests generated by the plugin itself (for secure internal loopback requests)
     */
    public static function sign_request($body) {
        $timestamp = time();
        $secret_key = self::get_secret_key();
        $data_to_sign = $timestamp . '.' . $body;
        $signature = hash_hmac('sha256', $data_to_sign, $secret_key);
        return array(
            'X-Timestamp' => (string)$timestamp,
            'X-Signature' => $signature
        );
    }
}

/**
 * Main Worker Plugin REST Controller Class
 */
class WPCentral_Worker_Controller {

    public function __construct() {
        add_action('rest_api_init', array($this, 'register_routes'));
    }

    /**
     * Register REST API routes under the wp-central/v1 namespace
     */
    public function register_routes() {
        register_rest_route('wp-central/v1', '/backup', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_backup_initiation'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/backup-process', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_background_backup_process'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/job-control', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_job_control'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/update', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_updates'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/job-status', array(
            'methods'             => WP_REST_Server::READABLE,
            'callback'            => array($this, 'get_job_status'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/status', array(
            'methods'             => WP_REST_Server::READABLE,
            'callback'            => array($this, 'get_wp_status'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/delete-backup', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_delete_backup'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));
    }

    /**
     * Job Control Endpoint (Pause, Kill)
     * POST /wp-json/wp-central/v1/job-control
     */
    public function handle_job_control(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $job_id = sanitize_text_field($params['job_id']);
        $action = sanitize_text_field($params['action']); // 'pause' or 'kill'

        $job_data = get_option('wp_central_job_' . $job_id);
        if ($job_data) {
            if ($action === 'pause') {
                $job_data['status'] = 'paused';
            } elseif ($action === 'kill') {
                $job_data['status'] = 'killed';
            }
            update_option('wp_central_job_' . $job_id, $job_data);
            return new WP_REST_Response(array('status' => 'ok', 'job' => $job_data), 200);
        }
        return new WP_Error('job_not_found', __('The specified background job was not found.', 'wp-central'), array('status' => 404));
    }

    /**
     * Return WordPress status, version, and pending updates count
     * GET /wp-json/wp-central/v1/status
     */
    /**
 * Return WordPress status, version, and complete pending updates count
 * GET /wp-json/wp-central/v1/status
 */
public function get_wp_status(WP_REST_Request $request) {
    // 1. Load administrative dependencies required for updates
    require_once ABSPATH . 'wp-admin/includes/update.php';
    require_once ABSPATH . 'wp-admin/includes/plugin.php';

    // 2. Clear update transients to force WordPress to fetch fresh data
    delete_site_transient('update_plugins');
    delete_site_transient('update_core');

    // 3. Force WordPress to query official repository and fire update hooks
    wp_version_check([], true);
    wp_update_plugins();

    // 4. Check Core updates
    $core_updates = get_core_updates();
    $pending_core = 0;
    if (!empty($core_updates) && isset($core_updates[0]->response) && $core_updates[0]->response === 'upgrade') {
        $pending_core = 1;
    }

    // 5. Retrieve all plugins needing updates
    $plugin_updates = get_plugin_updates();
    $pending_plugins = count($plugin_updates);

    // Build itemized list of pending plugins
    $plugin_list = array();
    foreach ($plugin_updates as $file => $data) {
        $plugin_list[] = array(
            'file'            => $file,
            'name'            => $data->Name,
            'current_version' => $data->Version,
            'new_version'     => isset($data->update->new_version) ? $data->update->new_version : 'Unknown'
        );
    }

    return new WP_REST_Response(array(
        'status'          => 'ok',
        'wp_version'      => get_bloginfo('version'),
        'pending_core'    => $pending_core,
        'pending_plugins' => $pending_plugins,
        'total_updates'   => $pending_core + $pending_plugins,
        'plugins_detail'  => $plugin_list
    ), 200);
}

    /**
     * Initiates non-blocking background backup (supports Local and S3 destinations)
     * POST /wp-json/wp-central/v1/backup
     */
    public function handle_backup_initiation(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $destination = isset($params['backup_destination']) ? sanitize_text_field($params['backup_destination']) : 's3';
        $s3_config = array();

        // Validate S3 inputs only if destination is set to cloud S3
        if ($destination === 's3') {
            $required = array('s3_bucket', 's3_endpoint', 's3_region', 's3_access_key', 's3_secret_key');
            foreach ($required as $field) {
                if (empty($params[$field])) {
                    return new WP_Error(
                        'missing_parameter',
                        sprintf(__('The parameter "%s" is required for S3 backup.', 'wp-central'), $field),
                        array('status' => 400)
                    );
                }
            }
            $s3_config = array(
                'bucket'     => sanitize_text_field($params['s3_bucket']),
                'endpoint'   => esc_url_raw($params['s3_endpoint']),
                'region'     => sanitize_text_field($params['s3_region']),
                'access_key' => sanitize_text_field($params['s3_access_key']),
                'secret_key' => sanitize_text_field($params['s3_secret_key'])
            );
        }

        // Generate unique Job ID
        $job_id = 'job_backup_' . time() . '_' . wp_generate_password(8, false);

        // Store Job State and configuration securely in options
        $job_data = array(
            'status'             => 'pending',
            'type'               => 'backup',
            'backup_destination' => $destination,
            'progress'           => 0,
            'created_at'         => time(),
            's3_config'          => $s3_config,
            'local_backup_path'  => isset($params['local_backup_path']) ? sanitize_text_field($params['local_backup_path']) : '',
            'archive_name'       => isset($params['archive_name']) ? sanitize_text_field($params['archive_name']) : ''
        );
        update_option('wp_central_job_' . $job_id, $job_data);

        $body = json_encode(array('job_id' => $job_id));
        $loopback_url = get_rest_url(null, '/wp-central/v1/backup-process');
        $parsed = parse_url($loopback_url);
        $host = isset($parsed['host']) ? $parsed['host'] : 'localhost';
        $port = isset($parsed['port']) ? $parsed['port'] : (isset($_SERVER['SERVER_PORT']) ? $_SERVER['SERVER_PORT'] : '80');

        // Path A: Internal Loopback URL
        $internal_url_a = 'http://127.0.0.1' . ($port ? ':' . $port : '') . (isset($parsed['path']) ? $parsed['path'] : '');
        if (isset($parsed['query'])) {
            $internal_url_a .= '?' . $parsed['query'];
        }

        // Dispatch Path A with a unique HMAC signature
        $headers_a = WPCentral_Security::sign_request($body);
        $headers_a['Content-Type'] = 'application/json';
        $headers_a['Host'] = $host;

        wp_remote_post($internal_url_a, array(
            'blocking'  => false,
            'sslverify' => false,
            'timeout'   => 0.1,
            'headers'   => $headers_a,
            'body'      => $body
        ));

        // Dispatch Path B (Public Endpoint) with its own fresh HMAC signature
        $headers_b = WPCentral_Security::sign_request($body);
        $headers_b['Content-Type'] = 'application/json';

        wp_remote_post($loopback_url, array(
            'blocking'  => false,
            'sslverify' => false,
            'timeout'   => 0.1,
            'headers'   => $headers_b,
            'body'      => $body
        ));

        // Return 202 Accepted instantly
        return new WP_REST_Response(array(
            'status' => 'accepted',
            'job_id' => $job_id
        ), 202);
    }

    /**
     * Executes the background backup process recursively
     * POST /wp-json/wp-central/v1/backup-process
     */
    public function handle_background_backup_process(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $job_id = sanitize_text_field($params['job_id']);
        $this->run_backup_process_inline($job_id);
        return new WP_REST_Response(array('status' => 'finished'), 200);
    }

    /**
     * Check if a job has been paused or killed.
     * Throws an exception to abort/suspend execution gracefully.
     */
    private function check_job_cancelled($job_id) {
        $job_data = get_option('wp_central_job_' . $job_id);
        if ($job_data) {
            if ($job_data['status'] === 'paused' || $job_data['status'] === 'killed') {
                throw new Exception("JOB_CANCELLED_OR_PAUSED");
            }
        }
    }

    /**
     * Core backup runner logic
     */
    private function run_backup_process_inline($job_id) {
        $job_data = get_option('wp_central_job_' . $job_id);
        if (!$job_data || ($job_data['status'] !== 'pending' && $job_data['status'] !== 'processing')) {
            return false;
        }

        @set_time_limit(0);
        if (function_exists('session_write_close')) {
            @session_write_close();
        }
        if (function_exists('ignore_user_abort')) {
            ignore_user_abort(true);
        }

        set_error_handler(function($severity, $message, $file, $line) {
            if (!(error_reporting() & $severity)) {
                return;
            }
            throw new ErrorException($message, 0, $severity, $file, $line);
        });

        $job_data['status'] = 'processing';
        $job_data['progress'] = 10;
        update_option('wp_central_job_' . $job_id, $job_data);

        $temp_dir = WP_CONTENT_DIR . '/uploads/wp-central-temp-' . $job_id;
        $sql_filepath = $temp_dir . '/db_backup.sql';
        $zip_filepath = $temp_dir . '/wp_content_backup.zip';
        $destination = isset($job_data['backup_destination']) ? $job_data['backup_destination'] : 's3';

        try {
            if (!file_exists($temp_dir)) {
                if (!mkdir($temp_dir, 0755, true)) {
                    throw new Exception("Failed to create temporary folder at: " . $temp_dir);
                }
            }

            $this->check_job_cancelled($job_id);

            // Step 1: Database Export
            $this->export_database($sql_filepath);
            $job_data['progress'] = 40;
            update_option('wp_central_job_' . $job_id, $job_data);

            $this->check_job_cancelled($job_id);

            // Step 2: Zip /wp-content/ directory
            $custom_local_vault = !empty($job_data['local_backup_path']) ? $job_data['local_backup_path'] : '';
            $this->zip_wp_content($zip_filepath, $sql_filepath, $temp_dir, $custom_local_vault);
            $job_data['progress'] = 70;
            update_option('wp_central_job_' . $job_id, $job_data);

            $this->check_job_cancelled($job_id);

            if ($destination === 's3') {
                // Step 3: Upload to S3
                $this->upload_to_s3_compatible($zip_filepath, $job_data['s3_config']);
                $this->recursive_cleanup($temp_dir);
                $final_path = 'S3 Cloud Storage Bucket: ' . $job_data['s3_config']['bucket'];
            } else {
                // Local Vault destination - support custom isolated path
                $local_vault = !empty($job_data['local_backup_path']) ? $job_data['local_backup_path'] : WP_CONTENT_DIR . '/uploads/wp-central-backups';
                if (!file_exists($local_vault)) {
                    if (!mkdir($local_vault, 0755, true)) {
                        throw new Exception("Failed to create local backups directory: " . $local_vault);
                    }
                }
                $local_archive_name = !empty($job_data['archive_name']) ? $job_data['archive_name'] : 'backup_' . $job_id . '.zip';
                $final_archive_path = rtrim($local_vault, '/\\') . '/' . $local_archive_name;

                if (!rename($zip_filepath, $final_archive_path)) {
                    throw new Exception("Failed to save zip to local backups folder.");
                }

                $this->recursive_cleanup($temp_dir);
                $final_path = $final_archive_path;
            }

            $job_data['status'] = 'completed';
            $job_data['progress'] = 100;
            $job_data['completed_at'] = time();
            $job_data['archive_name'] = basename($zip_filepath);
            $job_data['local_backup_path'] = $final_path;
            unset($job_data['s3_config']);
            update_option('wp_central_job_' . $job_id, $job_data);
            return true;
        } catch (Throwable $e) {
            $this->recursive_cleanup($temp_dir);
            if ($e->getMessage() === 'JOB_CANCELLED_OR_PAUSED') {
                return false;
            }

            $formatted_error = sprintf(
                "PHP Exception: %s inside file %s at line %d",
                $e->getMessage(),
                basename($e->getFile()),
                $e->getLine()
            );
            $job_data['status'] = 'failed';
            $job_data['error'] = $formatted_error;
            unset($job_data['s3_config']);
            update_option('wp_central_job_' . $job_id, $job_data);
            return false;
        } finally {
            restore_error_handler();
        }
    }

    /**
     * Core & Plugins Update Orchestrator
     * POST /wp-json/wp-central/v1/update
     */
    public function handle_updates(WP_REST_Request $request) {
    // 1. Force higher limits for this thread
    @ini_set('memory_limit', '512M');
    @set_time_limit(0);
    if (function_exists('session_write_close')) {
        @session_write_close();
    }

    // 2. Register shutdown function to catch silent fatal crashes
    register_shutdown_function(function() {
        $error = error_get_last();
        if ($error && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
            if (ob_get_length()) {
                ob_end_clean();
            }
            header('Content-Type: application/json', true, 500);
            echo json_encode([
                'status'  => 'error',
                'message' => sprintf('Fatal PHP Error: %s in %s on line %d', $error['message'], basename($error['file']), $error['line'])
            ]);
            exit;
        }
    });

    $params = $request->get_json_params();
    $type = sanitize_text_field($params['type']);

    try {
        $admin_users = get_users(['role' => 'Administrator']);
        $admin_id = (!empty($admin_users)) ? $admin_users[0]->ID : 1;
        wp_set_current_user($admin_id);

        if (!defined('WP_ADMIN')) {
            define('WP_ADMIN', true);
        }

        add_filter('filesystem_method', function() { return 'direct'; }, 9999);

        // Load WordPress Upgrader Dependencies explicitly
        require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
        require_once ABSPATH . 'wp-admin/includes/class-automatic-upgrader-skin.php';
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/plugin.php';
        require_once ABSPATH . 'wp-admin/includes/theme.php';
        require_once ABSPATH . 'wp-admin/includes/admin.php';
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        require_once ABSPATH . 'wp-admin/includes/plugin-install.php';
        require_once ABSPATH . 'wp-admin/includes/update.php';

        global $wp_filesystem;
        if (empty($wp_filesystem)) {
            ob_start();
            $creds = request_filesystem_credentials('', '', false, false, null);
            ob_end_clean();
            if (!WP_Filesystem($creds)) {
                if (!defined('FS_METHOD')) {
                    define('FS_METHOD', 'direct');
                }
                WP_Filesystem();
            }
        }

        if ($type === 'core') {
            wp_version_check();
            $updates = get_core_updates();

            if (empty($updates) || !isset($updates[0]->response) || $updates[0]->response !== 'upgrade') {
                return new WP_REST_Response([
                    'status'  => 'success',
                    'message' => 'WordPress Core is already up to date.'
                ], 200);
            }

            $upgrader = new Core_Upgrader(new Automatic_Upgrader_Skin());
            $result = $upgrader->upgrade($updates[0]);

            if (is_wp_error($result)) {
                return new WP_REST_Response([
                    'status'  => 'error',
                    'message' => 'Upgrader Error: ' . $result->get_error_message()
                ], 500);
            }

            return new WP_REST_Response([
                'status'  => 'success',
                'message' => 'WordPress Core updated successfully.'
            ], 200);

        } elseif ($type === 'plugin') {
            $plugins = $params['plugins'];
            if (empty($plugins) || !is_array($plugins)) {
                return new WP_REST_Response([
                    'status'  => 'error',
                    'message' => 'A valid list of plugins must be provided.'
                ], 400);
            }

            wp_update_plugins();
            $standard_upgrades = [];
            $custom_upgrades_results = [];
            $upgrader = new Plugin_Upgrader(new Automatic_Upgrader_Skin());

            foreach ($plugins as $plugin_item) {
                $plugin_file = is_string($plugin_item) ? sanitize_text_field($plugin_item) : (isset($plugin_item['file']) ? sanitize_text_field($plugin_item['file']) : '');
                $package_url = is_array($plugin_item) && isset($plugin_item['package_url']) ? esc_url_raw($plugin_item['package_url']) : '';

                if (empty($plugin_file)) continue;

                if (!empty($package_url)) {
                    $download_result = download_url($package_url);
                    if (is_wp_error($download_result)) {
                        $custom_upgrades_results[$plugin_file] = [
                            'status'  => 'error',
                            'message' => 'Download failed: ' . $download_result->get_error_message()
                        ];
                        continue;
                    }

                    $install_result = $upgrader->install($download_result, ['overwrite_package' => true]);

                    if (file_exists($download_result)) {
                        @unlink($download_result);
                    }

                    $custom_upgrades_results[$plugin_file] = is_wp_error($install_result) ? [
                        'status'  => 'error',
                        'message' => $install_result->get_error_message()
                    ] : [
                        'status'  => 'success',
                        'message' => 'Plugin updated successfully.'
                    ];
                } else {
                    $standard_upgrades[] = $plugin_file;
                }
            }

            $standard_results = null;
            if (!empty($standard_upgrades)) {
                $standard_results = $upgrader->bulk_upgrade($standard_upgrades);
            }

            wp_clean_plugins_cache(true);
            delete_site_transient('update_plugins');

            return new WP_REST_Response([
                'status'           => 'success',
                'message'          => 'Plugins update operation completed.',
                'custom_results'   => $custom_upgrades_results,
                'standard_results' => $standard_results
            ], 200);
        }

        return new WP_REST_Response(['status' => 'error', 'message' => 'Invalid update type.'], 400);

    } catch (Throwable $e) {
        return new WP_REST_Response([
            'status'  => 'error',
            'message' => sprintf('Exception: %s inside %s:%d', $e->getMessage(), basename($e->getFile()), $e->getLine())
        ], 500);
    }
}

    /**
     * Poll status endpoint for asynchronous jobs
     * GET /wp-json/wp-central/v1/job-status
     */
    public function get_job_status(WP_REST_Request $request) {
        $job_id = sanitize_text_field($request->get_param('job_id'));
        if (empty($job_id)) {
            return new WP_Error(
                'missing_job_id',
                __('Missing job_id parameter.', 'wp-central'),
                array('status' => 400)
            );
        }

        $job_data = get_option('wp_central_job_' . $job_id);
        if (!$job_data) {
            return new WP_Error(
                'job_not_found',
                __('The specified background job was not found.', 'wp-central'),
                array('status' => 404)
            );
        }

        if ($job_data['status'] === 'pending' && (time() - intval($job_data['created_at'])) > 5) {
            $this->run_backup_process_inline($job_id);
            $job_data = get_option('wp_central_job_' . $job_id);
        }

        return new WP_REST_Response($job_data, 200);
    }

    /**
     * Handle deleting local backup zip files and S3 backup objects using the built-in AWS Signature V4 client.
     * POST /wp-json/wp-central/v1/delete-backup
     */
    public function handle_delete_backup(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $destination = isset($params['destination']) ? sanitize_text_field($params['destination']) : 'local';
        $local_path = isset($params['localPath']) ? sanitize_text_field($params['localPath']) : '';
        $s3_key = isset($params['s3Key']) ? sanitize_text_field($params['s3Key']) : '';
        $s3_config = isset($params['s3Config']) ? $params['s3Config'] : array();
        $custom_local_vault = isset($params['customLocalVault']) ? sanitize_text_field($params['customLocalVault']) : '';

        if ($destination === 'local') {
            if (empty($local_path)) {
                return new WP_Error('missing_path', __('Missing localPath parameter.', 'wp-central'), array('status' => 400));
            }
            // Sanity check to prevent directory traversal
            $local_path = wp_normalize_path($local_path);
            $local_vault = wp_normalize_path(WP_CONTENT_DIR . '/uploads/wp-central-backups');
            $custom_vault_normalized = !empty($custom_local_vault) ? wp_normalize_path($custom_local_vault) : '';

            $is_allowed = (strpos($local_path, $local_vault) === 0);
            if (!$is_allowed && !empty($custom_vault_normalized)) {
                $is_allowed = (strpos($local_path, $custom_vault_normalized) === 0);
            }

            // Also check for directory traversal via '..'
            if (!$is_allowed || strpos($local_path, '..') !== false) {
                return new WP_Error('invalid_path', __('Invalid local backup path.', 'wp-central'), array('status' => 400));
            }

            if (file_exists($local_path)) {
                @unlink($local_path);
                return new WP_REST_Response(array('status' => 'success', 'message' => 'Local backup zip file deleted successfully.'), 200);
            } else {
                return new WP_REST_Response(array('status' => 'success', 'message' => 'Local backup zip file was not found but cataloged as deleted.'), 200);
            }
        } elseif ($destination === 's3') {
            if (empty($s3_key)) {
                return new WP_Error('missing_s3_key', __('Missing s3Key parameter.', 'wp-central'), array('status' => 400));
            }
            if (empty($s3_config)) {
                return new WP_Error('missing_s3_config', __('Missing s3Config parameter.', 'wp-central'), array('status' => 400));
            }

            try {
                $this->delete_from_s3_compatible($s3_key, $s3_config);
                return new WP_REST_Response(array('status' => 'success', 'message' => 'S3 backup object deleted successfully.'), 200);
            } catch (Exception $e) {
                return new WP_Error('s3_delete_error', $e->getMessage(), array('status' => 500));
            }
        }

        return new WP_Error('invalid_destination', __('Invalid destination specified.', 'wp-central'), array('status' => 400));
    }

    /**
     * Delete object from S3 using pure PHP Signature V4 AWS REST Client
     */
    private function delete_from_s3_compatible($s3_key, $s3_config) {
        $bucket = $s3_config['bucket'];
        $endpoint = rtrim($s3_config['endpoint'], '/');
        $region = $s3_config['region'];
        $access_key = $s3_config['access_key'];
        $secret_key = $s3_config['secret_key'];

        $host = parse_url($endpoint, PHP_URL_HOST);
        $timestamp = gmdate('Ymd\THis\Z');
        $date = substr($timestamp, 0, 8);

        // Ensure key begins with single slash or bucket path
        $object_name = ltrim($s3_key, '/');
        $request_uri = '/' . $bucket . '/' . $object_name;
        $request_url = $endpoint . '/' . $bucket . '/' . $object_name;

        $payload_hash = hash('sha256', '');
        $headers = array(
            'host'                 => $host,
            'x-amz-content-sha256' => $payload_hash,
            'x-amz-date'           => $timestamp,
        );

        ksort($headers);
        $canonical_headers = '';
        foreach ($headers as $k => $v) {
            $canonical_headers .= $k . ':' . trim($v) . "\n";
        }

        $signed_headers = implode(';', array_keys($headers));
        $canonical_request = "DELETE\n" .
                             $request_uri . "\n" .
                             "" . "\n" .
                             $canonical_headers . "\n" .
                             $signed_headers . "\n" .
                             $payload_hash;

        $algorithm = 'AWS4-HMAC-SHA256';
        $credential_scope = $date . '/' . $region . '/s3/aws4_request';
        $string_to_sign = $algorithm . "\n" .
                          $timestamp . "\n" .
                          $credential_scope . "\n" .
                          hash('sha256', $canonical_request);

        $k_date = hash_hmac('sha256', $date, 'AWS4' . $secret_key, true);
        $k_region = hash_hmac('sha256', $region, $k_date, true);
        $k_service = hash_hmac('sha256', 's3', $k_region, true);
        $k_signing = hash_hmac('sha256', 'aws4_request', $k_service, true);
        $signature = hash_hmac('sha256', $string_to_sign, $k_signing);

        $authorization = "$algorithm Credential=$access_key/$credential_scope, SignedHeaders=$signed_headers, Signature=$signature";

        $args = array(
            'method'    => 'DELETE',
            'headers'   => array(
                'Host'                 => $host,
                'x-amz-content-sha256' => $payload_hash,
                'x-amz-date'           => $timestamp,
                'Authorization'        => $authorization
            ),
            'timeout'   => 60,
            'sslverify' => false
        );

        $response = wp_remote_request($request_url, $args);

        if (is_wp_error($response)) {
            throw new Exception("S3 Delete Transmission Error: " . $response->get_error_message());
        }

        $status_code = wp_remote_retrieve_response_code($response);
        if ($status_code < 200 || $status_code >= 300) {
            if ($status_code === 404) {
                return true; // Already deleted or not found
            }
            $response_body = wp_remote_retrieve_body($response);
            throw new Exception("S3 DELETE API rejection. Status: {$status_code}. Response: {$response_body}");
        }

        return true;
    }

    /**
     * Helper to check if CLI command execution is allowed/enabled on this server.
     */
    private function is_exec_enabled() {
        if (!function_exists('exec')) {
            return false;
        }
        $disabled_str = ini_get('disable_functions');
        if (empty($disabled_str)) {
            return true;
        }
        $disabled = array_map('trim', explode(',', $disabled_str));
        return !in_array('exec', $disabled) && !in_array('shell_exec', $disabled);
    }

    /**
     * Database Dumper
     */
    private function export_database($filepath) {
        global $wpdb;

        // Fast Path: Check if native CLI execution is allowed/enabled, and run optimized mysqldump
        if ($this->is_exec_enabled()) {
            $host_parts = explode(':', DB_HOST);
            $db_host = $host_parts[0];
            $db_port = isset($host_parts[1]) ? $host_parts[1] : '';

            $cmd = 'mysqldump';
            if (!empty($db_host)) {
                $cmd .= ' -h ' . escapeshellarg($db_host);
            }
            if (!empty($db_port) && is_numeric($db_port)) {
                $cmd .= ' -P ' . escapeshellarg($db_port);
            }
            $cmd .= ' -u ' . escapeshellarg(DB_USER);
            if (defined('DB_PASSWORD') && !empty(DB_PASSWORD)) {
                $cmd .= ' -p' . escapeshellarg(DB_PASSWORD);
            }
            $cmd .= ' --single-transaction --quick --opt ' . escapeshellarg(DB_NAME) . ' > ' . escapeshellarg($filepath);

            exec($cmd, $output, $return_var);
            if ($return_var === 0 && file_exists($filepath) && filesize($filepath) > 0) {
                return true; // Fast path successful!
            }
        }

        // Optimized Pure-PHP SQL Exporter Fallback
        $wpdb->save_queries = false;
        $wpdb->suppress_errors(true);

        $tables = $wpdb->get_col("SHOW TABLES");
        $handle = fopen($filepath, 'w');
        if (!$handle) {
            throw new Exception("Unable to open SQL file for writing at: " . $filepath);
        }

        fwrite($handle, "-- WP Central Database Backup\n-- Date: " . date('Y-m-d H:i:s') . "\n\n");
        fwrite($handle, "SET FOREIGN_KEY_CHECKS = 0;\nSET UNIQUE_CHECKS = 0;\nSET AUTOCOMMIT = 0;\n\n");

        foreach ($tables as $table) {
            $create_table = $wpdb->get_row("SHOW CREATE TABLE `$table`", ARRAY_N);
            fwrite($handle, "DROP TABLE IF EXISTS `$table`;\n" . $create_table[1] . ";\n\n");

            // Identify the primary key and verify if it's numeric for Primary Key pagination
            $primary_key = '';
            $is_numeric_pk = false;
            $col_info = $wpdb->get_results("SHOW COLUMNS FROM `$table`", ARRAY_A);
            if (!empty($col_info)) {
                foreach ($col_info as $col) {
                    if ($col['Key'] === 'PRI') {
                        $primary_key = $col['Field'];
                        $type = strtolower($col['Type']);
                        if (strpos($type, 'int') !== false || strpos($type, 'decimal') !== false || strpos($type, 'num') !== false) {
                            $is_numeric_pk = true;
                        }
                        break;
                    }
                }
            }

            if (!empty($primary_key) && $is_numeric_pk) {
                // Primary Key Range Query Pagination (No OFFSET)
                $last_id = 0;
                $batch_values = array();
                $keys = array();

                while (true) {
                    $rows = $wpdb->get_results($wpdb->prepare(
                        "SELECT * FROM `$table` WHERE `$primary_key` > %d ORDER BY `$primary_key` ASC LIMIT 2000",
                        $last_id
                    ), ARRAY_A);

                    if (empty($rows)) {
                        break;
                    }

                    foreach ($rows as $row) {
                        if (empty($keys)) {
                            $keys = array_map(function($k) { return "`$k`"; }, array_keys($row));
                        }
                        $escaped_values = array_map(function($val) {
                            return is_null($val) ? 'NULL' : "'" . esc_sql($val) . "'";
                        }, array_values($row));
                        $batch_values[] = "(" . implode(', ', $escaped_values) . ")";

                        if (count($batch_values) >= 1000) {
                            fwrite($handle, "INSERT INTO `$table` (" . implode(', ', $keys) . ") VALUES " . implode(', ', $batch_values) . ";\n");
                            $batch_values = array();
                        }
                    }

                    $last_row = end($rows);
                    $last_id = intval($last_row[$primary_key]);
                }

                if (!empty($batch_values)) {
                    fwrite($handle, "INSERT INTO `$table` (" . implode(', ', $keys) . ") VALUES " . implode(', ', $batch_values) . ";\n");
                }
            } else {
                // Standard offset chunk fallback if no numeric PRI is found
                $count = $wpdb->get_var("SELECT COUNT(*) FROM `$table`");
                $chunk_size = 1000;
                $batch_values = array();
                $keys = array();

                for ($offset = 0; $offset < $count; $offset += $chunk_size) {
                    $rows = $wpdb->get_results("SELECT * FROM `$table` LIMIT $chunk_size OFFSET $offset", ARRAY_A);
                    foreach ($rows as $row) {
                        if (empty($keys)) {
                            $keys = array_map(function($k) { return "`$k`"; }, array_keys($row));
                        }
                        $escaped_values = array_map(function($val) {
                            return is_null($val) ? 'NULL' : "'" . esc_sql($val) . "'";
                        }, array_values($row));
                        $batch_values[] = "(" . implode(', ', $escaped_values) . ")";

                        if (count($batch_values) >= 1000) {
                            fwrite($handle, "INSERT INTO `$table` (" . implode(', ', $keys) . ") VALUES " . implode(', ', $batch_values) . ";\n");
                            $batch_values = array();
                        }
                    }
                }

                if (!empty($batch_values)) {
                    fwrite($handle, "INSERT INTO `$table` (" . implode(', ', $keys) . ") VALUES " . implode(', ', $batch_values) . ";\n");
                }
            }
            fwrite($handle, "\n\n");
        }

        fwrite($handle, "COMMIT;\nSET FOREIGN_KEY_CHECKS = 1;\nSET UNIQUE_CHECKS = 1;\n");
        fclose($handle);
    }

    /**
     * Zip recursive worker excluding workspace directory
     */
    private function zip_wp_content($zip_filepath, $sql_filepath, $exclude_dir, $custom_local_vault = '') {
        // Fast Path: Check if native CLI zip is allowed/enabled and run it
        if ($this->is_exec_enabled()) {
            exec('which zip', $out, $code);
            if ($code === 0) {
                $parent_dir = dirname(WP_CONTENT_DIR);
                $wp_content_dirname = basename(WP_CONTENT_DIR);

                // Exclude temp backups directories relative to parent of wp-content
                $cmd = 'cd ' . escapeshellarg($parent_dir) . ' && zip -r ' . escapeshellarg($zip_filepath) . ' ' . escapeshellarg($wp_content_dirname) . ' -x "' . $wp_content_dirname . '/uploads/*"';
                exec($cmd, $output, $return_var);

                if ($return_var === 0 && file_exists($zip_filepath) && filesize($zip_filepath) > 0) {
                    $cmd_sql = 'zip -j ' . escapeshellarg($zip_filepath) . ' ' . escapeshellarg($sql_filepath);
                    exec($cmd_sql, $output_sql, $return_var_sql);
                    if ($return_var_sql === 0) {
                        return true; // Fast path archive successful!
                    }
                }
            }
        }

        // Pure PHP ZipArchive Fallback
        if (!class_exists('ZipArchive')) {
            throw new Exception("ZipArchive PHP extension is not installed on this server.");
        }

        $zip = new ZipArchive();
        if ($zip->open($zip_filepath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception("Could not create ZIP archive at: " . $zip_filepath);
        }

        $wp_content_dir = wp_normalize_path(rtrim(WP_CONTENT_DIR, '/\\'));
        $norm_exclude_dir = wp_normalize_path($exclude_dir);
        $norm_backups_dir = wp_normalize_path(WP_CONTENT_DIR . '/uploads/wp-central-backups');
        $norm_uploads_dir = wp_normalize_path(WP_CONTENT_DIR . '/uploads');
        $norm_custom_vault = !empty($custom_local_vault) ? wp_normalize_path($custom_local_vault) : '';

        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($wp_content_dir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::LEAVES_ONLY
        );

        foreach ($files as $file) {
            if (!$file->isDir()) {
                $real_path = wp_normalize_path($file->getRealPath());

                // Skip current temp directory, local backup vault, custom backup vault, and the heavy uploads folder
                if ($real_path && (
                    strpos($real_path, $norm_exclude_dir) === 0 ||
                    strpos($real_path, $norm_backups_dir) === 0 ||
                    strpos($real_path, $norm_uploads_dir) === 0 ||
                    (!empty($norm_custom_vault) && strpos($real_path, $norm_custom_vault) === 0)
                )) {
                    continue;
                }

                if (!is_readable($real_path)) {
                    continue;
                }

                $relative_path = substr($real_path, strlen($wp_content_dir) + 1);
                $zip->addFile($real_path, 'wp-content/' . $relative_path);
            }
        }

        $zip->addFile($sql_filepath, 'database_dump.sql');
        $zip->close();
    }

    /**
     * AWS Signature V4 S3 client
     */
    private function upload_to_s3_compatible($filepath, $s3_config) {
        $bucket = $s3_config['bucket'];
        $endpoint = rtrim($s3_config['endpoint'], '/');
        $region = $s3_config['region'];
        $access_key = $s3_config['access_key'];
        $secret_key = $s3_config['secret_key'];
        $object_name = basename($filepath);

        $file_content = file_get_contents($filepath);
        if ($file_content === false) {
            throw new Exception("Unable to read backup zip archive for upload.");
        }

        $payload_hash = hash('sha256', $file_content);
        $host = parse_url($endpoint, PHP_URL_HOST);
        $timestamp = gmdate('Ymd\THis\Z');
        $date = substr($timestamp, 0, 8);

        $request_uri = '/' . $bucket . '/' . $object_name;
        $request_url = $endpoint . '/' . $bucket . '/' . $object_name;

        $headers = array(
            'content-type'         => 'application/octet-stream',
            'host'                 => $host,
            'x-amz-content-sha256' => $payload_hash,
            'x-amz-date'           => $timestamp,
        );

        ksort($headers);
        $canonical_headers = '';
        foreach ($headers as $k => $v) {
            $canonical_headers .= $k . ':' . trim($v) . "\n";
        }

        $signed_headers = implode(';', array_keys($headers));
        $canonical_request = "PUT\n" .
                             $request_uri . "\n" .
                             "" . "\n" .
                             $canonical_headers . "\n" .
                             $signed_headers . "\n" .
                             $payload_hash;

        $algorithm = 'AWS4-HMAC-SHA256';
        $credential_scope = $date . '/' . $region . '/s3/aws4_request';
        $string_to_sign = $algorithm . "\n" .
                          $timestamp . "\n" .
                          $credential_scope . "\n" .
                          hash('sha256', $canonical_request);

        $k_date = hash_hmac('sha256', $date, 'AWS4' . $secret_key, true);
        $k_region = hash_hmac('sha256', $region, $k_date, true);
        $k_service = hash_hmac('sha256', 's3', $k_region, true);
        $k_signing = hash_hmac('sha256', 'aws4_request', $k_service, true);
        $signature = hash_hmac('sha256', $string_to_sign, $k_signing);

        $authorization = "$algorithm Credential=$access_key/$credential_scope, SignedHeaders=$signed_headers, Signature=$signature";

        $args = array(
            'method'    => 'PUT',
            'headers'   => array(
                'Content-Type'         => 'application/octet-stream',
                'Host'                 => $host,
                'x-amz-content-sha256' => $payload_hash,
                'x-amz-date'           => $timestamp,
                'Authorization'        => $authorization
            ),
            'body'      => $file_content,
            'timeout'   => 600,
            'sslverify' => false
        );

        $response = wp_remote_request($request_url, $args);

        if (is_wp_error($response)) {
            throw new Exception("S3 Transmission Error: " . $response->get_error_message());
        }

        $status_code = wp_remote_retrieve_response_code($response);
        if ($status_code < 200 || $status_code >= 300) {
            $response_body = wp_remote_retrieve_body($response);
            throw new Exception("S3 API rejection. Status: {$status_code}. Response: {$response_body}");
        }

        return true;
    }

    private function recursive_cleanup($dir) {
        if (!file_exists($dir)) {
            return;
        }
        $files = array_diff(scandir($dir), array('.', '..'));
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            if (is_dir($path)) {
                $this->recursive_cleanup($path);
            } else {
                unlink($path);
            }
        }
        rmdir($dir);
    }
}

new WPCentral_Worker_Controller();