<?php
/**
 * Plugin Name: WP Central Worker Plugin
 * Description: Lightweight WordPress worker plugin for Central WordPress Management System. Supports secure HMAC-SHA256 authentication, asynchronous backups to S3, automated updates, and custom plugin vault sideloading.
 * Version: 1.1.1
 * Author: WP Central Team
 * License: GPL2
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

/**
 * Security & Authentication Helper Class
 */
class WPCentral_Security {
    private static $secret_key_option_name = 'wp_central_secret_key';

    public static function get_secret_key() {
        $secret = get_option(self::$secret_key_option_name);
        if (!$secret) {
            // Fallback for demo or initialization
            $secret = defined('WP_CENTRAL_SECRET_KEY') ? WP_CENTRAL_SECRET_KEY : 'default_secret_key_12345';
        }
        return $secret;
    }

    public static function set_secret_key($key) {
        update_option(self::$secret_key_option_name, $key);
    }

    /**
     * Reconstruct and verify the HMAC-SHA256 signature
     */
    public static function verify_request(WP_REST_Request $request) {
        $signature = $request->get_header('X-Signature');
        $timestamp = intval($request->get_header('X-Timestamp'));

        if (empty($signature) || empty($timestamp)) {
            return new WP_Error(
                'rest_forbidden',
                __('Missing signature or timestamp headers.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 1. Prevent Replay: Check clock drift (max 5 minutes)
        if (abs(time() - $timestamp) > 300) {
            return new WP_Error(
                'rest_forbidden',
                __('Request expired. Clock drift too high.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 2. Prevent Replay: Verify signature hasn't been used before
        $transient_key = 'wp_central_sig_' . md5($signature);
        if (get_transient($transient_key)) {
            return new WP_Error(
                'rest_forbidden',
                __('Replay attack detected. Signature already used.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 3. Verify Signature
        $raw_body = $request->get_body();
        $data_to_sign = $timestamp . '.' . $raw_body;
        $secret_key = self::get_secret_key();
        $expected_signature = hash_hmac('sha256', $data_to_sign, $secret_key);

        if (!hash_equals($expected_signature, $signature)) {
            return new WP_Error(
                'rest_forbidden',
                __('Invalid signature.', 'wp-central'),
                array('status' => 403)
            );
        }

        // Store the signature in transient to prevent replay for the duration of its validity (5 minutes)
        set_transient($transient_key, true, 300);

        return true;
    }

    /**
     * Sign requests generated by the plugin itself (for secure internal loopback requests)
     */
    public static function sign_request($body) {
        $timestamp = time();
        $secret_key = self::get_secret_key();
        $data_to_sign = $timestamp . '.' . $body;
        $signature = hash_hmac('sha256', $data_to_sign, $secret_key);
        return array(
            'X-Timestamp' => $timestamp,
            'X-Signature' => $signature
        );
    }
}

/**
 * Main Worker Plugin REST Controller Class
 */
class WPCentral_Worker_Controller {

    public function __construct() {
        add_action('rest_api_init', array($this, 'register_routes'));
    }

    /**
     * Register REST API routes under the wp-central/v1 namespace
     */
    public function register_routes() {
        register_rest_route('wp-central/v1', '/backup', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_backup_initiation'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/backup-process', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_background_backup_process'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/update', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_updates'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/job-status', array(
            'methods'             => WP_REST_Server::READABLE,
            'callback'            => array($this, 'get_job_status'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));
    }

    /**
     * Initiates non-blocking background backup
     * POST /wp-json/wp-central/v1/backup
     */
    public function handle_backup_initiation(WP_REST_Request $request) {
        $params = $request->get_json_params();

        // Validate S3 inputs
        $required = array('s3_bucket', 's3_endpoint', 's3_region', 's3_access_key', 's3_secret_key');
        foreach ($required as $field) {
            if (empty($params[$field])) {
                return new WP_Error(
                    'missing_parameter',
                    sprintf(__('The parameter "%s" is required.', 'wp-central'), $field),
                    array('status' => 400)
                );
            }
        }

        // Generate unique Job ID
        $job_id = 'job_backup_' . time() . '_' . wp_generate_password(8, false);

        // Store Job State and configuration securely in options
        $job_data = array(
            'status'     => 'pending',
            'type'       => 'backup',
            'progress'   => 0,
            'created_at' => time(),
            's3_config'  => array(
                'bucket'     => sanitize_text_field($params['s3_bucket']),
                'endpoint'   => esc_url_raw($params['s3_endpoint']),
                'region'     => sanitize_text_field($params['s3_region']),
                'access_key' => sanitize_text_field($params['s3_access_key']),
                'secret_key' => sanitize_text_field($params['s3_secret_key'])
            )
        );
        update_option('wp_central_job_' . $job_id, $job_data);

        // Trigger Asynchronous loopback request to run the backup process non-blocking
        $loopback_url = get_rest_url(null, '/wp-central/v1/backup-process');
        $body = json_encode(array('job_id' => $job_id));
        $headers = WPCentral_Security::sign_request($body);
        $headers['Content-Type'] = 'application/json';

        // Fire and forget: very low timeout and blocking false ensures instant response
        wp_remote_post($loopback_url, array(
            'blocking'  => false,
            'sslverify' => false,
            'timeout'   => 0.1,
            'headers'   => $headers,
            'body'      => $body
        ));

        // Return 202 Accepted instantly
        return new WP_REST_Response(array(
            'status' => 'accepted',
            'job_id' => $job_id
        ), 202);
    }

    /**
     * Executes the background backup process recursively
     * POST /wp-json/wp-central/v1/backup-process
     */
    public function handle_background_backup_process(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $job_id = sanitize_text_field($params['job_id']);

        $job_data = get_option('wp_central_job_' . $job_id);
        if (!$job_data || $job_data['status'] !== 'pending') {
            return new WP_REST_Response(array('status' => 'ignored'), 200);
        }

        // Set limits and status to processing
        set_time_limit(0);
        ignore_user_abort(true);

        $job_data['status'] = 'processing';
        $job_data['progress'] = 10;
        update_option('wp_central_job_' . $job_id, $job_data);

        $temp_dir = WP_CONTENT_DIR . '/uploads/wp-central-temp-' . $job_id;
        $sql_filepath = $temp_dir . '/db_backup.sql';
        $zip_filepath = $temp_dir . '/wp_content_backup.zip';

        try {
            // Create temporary workspace
            if (!file_exists($temp_dir)) {
                mkdir($temp_dir, 0755, true);
            }

            // Step 1: Database Export (Pure PHP SQL Dumper fallback-free/highly-portable)
            $this->export_database($sql_filepath);

            $job_data['progress'] = 40;
            update_option('wp_central_job_' . $job_id, $job_data);

            // Step 2: Zip /wp-content/ directory excluding current temporary workspace
            $this->zip_wp_content($zip_filepath, $sql_filepath, $temp_dir);

            $job_data['progress'] = 70;
            update_option('wp_central_job_' . $job_id, $job_data);

            // Step 3: Upload to S3 using self-contained AWS Sign V4 REST client
            $this->upload_to_s3_compatible($zip_filepath, $job_data['s3_config']);

            // Cleanup workspace
            $this->recursive_cleanup($temp_dir);

            // Set job to completed
            $job_data['status'] = 'completed';
            $job_data['progress'] = 100;
            $job_data['completed_at'] = time();
            $job_data['archive_name'] = basename($zip_filepath);
            // Hide sensitive config before final storage
            unset($job_data['s3_config']);
            update_option('wp_central_job_' . $job_id, $job_data);

        } catch (Exception $e) {
            // Local cleanup on failure
            $this->recursive_cleanup($temp_dir);

            $job_data['status'] = 'failed';
            $job_data['error'] = $e->getMessage();
            unset($job_data['s3_config']);
            update_option('wp_central_job_' . $job_id, $job_data);
        }

        return new WP_REST_Response(array('status' => 'finished'), 200);
    }

    /**
     * Core & Plugins Update Orchestrator
     * POST /wp-json/wp-central/v1/update
     */
    public function handle_updates(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $type = sanitize_text_field($params['type']); // 'core' or 'plugin'

        // Load WordPress administrative upgrader utilities
        require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/plugin.php';
        require_once ABSPATH . 'wp-admin/includes/admin.php';

        // Force FS_METHOD 'direct' to bypass prompt credentials
        if (!defined('FS_METHOD')) {
            define('FS_METHOD', 'direct');
        }
        add_filter('request_filesystem_credentials', '__return_true', 100);

        if ($type === 'core') {
            $upgrader = new Core_Upgrader(new Automatic_Upgrader_Skin());
            $updates = get_core_updates();

            if (empty($updates)) {
                return new WP_REST_Response(array(
                    'status'  => 'success',
                    'message' => 'WordPress Core is already up to date.'
                ), 200);
            }

            $result = $upgrader->upgrade($updates[0]);
            if (is_wp_error($result)) {
                return new WP_REST_Response(array(
                    'status'  => 'error',
                    'message' => $result->get_error_message()
                ), 500);
            }

            return new WP_REST_Response(array(
                'status'  => 'success',
                'message' => 'WordPress Core updated successfully.',
                'result'  => $result
            ), 200);

        } elseif ($type === 'plugin') {
            $plugins = $params['plugins']; // Array of strings or objects: e.g., [{"file": "akismet/akismet.php", "package_url": "..."}]
            if (empty($plugins) || !is_array($plugins)) {
                return new WP_REST_Response(array(
                    'status'  => 'error',
                    'message' => 'A valid list of plugins must be provided.'
                ), 400);
            }

            $standard_upgrades = array();
            $custom_upgrades_results = array();

            // Initialize Plugin Upgrader with silent automatic skin
            $upgrader = new Plugin_Upgrader(new Automatic_Upgrader_Skin());

            foreach ($plugins as $plugin_item) {
                $plugin_file = '';
                $package_url = '';

                // Handle both simple formats (string) and custom vault formats (object)
                if (is_string($plugin_item)) {
                    $plugin_file = sanitize_text_field($plugin_item);
                } elseif (is_array($plugin_item)) {
                    $plugin_file = isset($plugin_item['file']) ? sanitize_text_field($plugin_item['file']) : '';
                    $package_url = isset($plugin_item['package_url']) ? esc_url_raw($plugin_item['package_url']) : '';
                }

                if (empty($plugin_file)) {
                    continue;
                }

                // If package_url is present, this is a premium/custom plugin sideload!
                if (!empty($package_url)) {
                    $download_result = download_url($package_url);

                    if (is_wp_error($download_result)) {
                        $custom_upgrades_results[$plugin_file] = array(
                            'status'  => 'error',
                            'message' => 'Failed to download custom package zip: ' . $download_result->get_error_message()
                        );
                        continue;
                    }

                    // Trigger direct local zip installation/overwrite
                    $install_result = $upgrader->install($download_result, array('overwrite_package' => true));

                    // Secure local cleanup of temporary download archive
                    if (file_exists($download_result)) {
                        @unlink($download_result);
                    }

                    if (is_wp_error($install_result)) {
                        $custom_upgrades_results[$plugin_file] = array(
                            'status'  => 'error',
                            'message' => $install_result->get_error_message()
                        );
                    } else {
                        $custom_upgrades_results[$plugin_file] = array(
                            'status'  => 'success',
                            'message' => 'Sideloaded premium plugin updated successfully.'
                        );
                    }
                } else {
                    // Standard public WordPress.org repository plugin
                    $standard_upgrades[] = $plugin_file;
                }
            }

            // Run standard public bulk upgrades
            $standard_results = null;
            if (!empty($standard_upgrades)) {
                $standard_results = $upgrader->bulk_upgrade($standard_upgrades);
            }

            return new WP_REST_Response(array(
                'status'           => 'success',
                'message'          => 'Plugins update operation completed.',
                'custom_results'   => $custom_upgrades_results,
                'standard_results' => $standard_results
            ), 200);
        }

        return new WP_REST_Response(array(
            'status'  => 'error',
            'message' => 'Invalid update type specified.'
        ), 400);
    }

    /**
     * Poll status endpoint for asynchronous jobs
     * GET /wp-json/wp-central/v1/job-status
     */
    public function get_job_status(WP_REST_Request $request) {
        $job_id = sanitize_text_field($request->get_param('job_id'));
        if (empty($job_id)) {
            return new WP_Error(
                'missing_job_id',
                __('Missing job_id parameter.', 'wp-central'),
                array('status' => 400)
            );
        }

        $job_data = get_option('wp_central_job_' . $job_id);
        if (!$job_data) {
            return new WP_Error(
                'job_not_found',
                __('The specified background job was not found.', 'wp-central'),
                array('status' => 404)
            );
        }

        return new WP_REST_Response($job_data, 200);
    }

    /**
     * Pure PHP robust database dumper
     */
    private function export_database($filepath) {
        global $wpdb;
        $tables = $wpdb->get_col("SHOW TABLES");
        $sql_content = "-- WP Central Database Backup\n-- Date: " . date('Y-m-d H:i:s') . "\n\n";

        foreach ($tables as $table) {
            $create_table = $wpdb->get_row("SHOW CREATE TABLE `$table`", ARRAY_N);
            $sql_content .= "DROP TABLE IF EXISTS `$table`;\n";
            $sql_content .= $create_table[1] . ";\n\n";

            $rows = $wpdb->get_results("SELECT * FROM `$table`", ARRAY_A);
            foreach ($rows as $row) {
                $escaped_values = array();
                foreach ($row as $val) {
                    if (is_null($val)) {
                        $escaped_values[] = 'NULL';
                    } else {
                        $escaped_values[] = "'" . esc_sql($val) . "'";
                    }
                }
                $keys = array_map(function($k) { return "`$k`"; }, array_keys($row));
                $sql_content .= "INSERT INTO `$table` (" . implode(', ', $keys) . ") VALUES (" . implode(', ', $escaped_values) . ");\n";
            }
            $sql_content .= "\n\n";
        }

        if (file_put_contents($filepath, $sql_content) === false) {
            throw new Exception("Unable to write SQL database backup file.");
        }
    }

    /**
     * Zip recursive worker excluding specific workspace path
     */
    private function zip_wp_content($zip_filepath, $sql_filepath, $exclude_dir) {
        $zip = new ZipArchive();
        if ($zip->open($zip_filepath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new Exception("Could not create ZIP archive at: " . $zip_filepath);
        }

        $wp_content_dir = rtrim(WP_CONTENT_DIR, '/\\');
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($wp_content_dir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::LEAVES_ONLY
        );

        foreach ($files as $file) {
            if (!$file->isDir()) {
                $real_path = $file->getRealPath();

                // Exclude temporary directory to prevent recursive loop nesting
                if (strpos($real_path, $exclude_dir) === 0) {
                    continue;
                }

                $relative_path = substr($real_path, strlen($wp_content_dir) + 1);
                $zip->addFile($real_path, 'wp-content/' . $relative_path);
            }
        }

        // Add the SQL database backup into the root of the archive
        $zip->addFile($sql_filepath, 'database_dump.sql');
        $zip->close();
    }

    /**
     * Lightweight AWS Signature V4 S3 compatibility REST client
     */
    private function upload_to_s3_compatible($filepath, $s3_config) {
        $bucket = $s3_config['bucket'];
        $endpoint = rtrim($s3_config['endpoint'], '/');
        $region = $s3_config['region'];
        $access_key = $s3_config['access_key'];
        $secret_key = $s3_config['secret_key'];
        $object_name = basename($filepath);

        $file_content = file_get_contents($filepath);
        if ($file_content === false) {
            throw new Exception("Unable to read backup zip archive for upload.");
        }

        $payload_hash = hash('sha256', $file_content);
        $host = parse_url($endpoint, PHP_URL_HOST);
        $timestamp = gmdate('Ymd\THis\Z');
        $date = substr($timestamp, 0, 8);

        // Canonical structures for Signature V4
        $request_uri = '/' . $bucket . '/' . $object_name;
        $request_url = $endpoint . '/' . $bucket . '/' . $object_name;

        $headers = array(
            'content-type'         => 'application/octet-stream',
            'host'                 => $host,
            'x-amz-content-sha256' => $payload_hash,
            'x-amz-date'           => $timestamp,
        );

        // Sort headers alphabetically
        ksort($headers);

        $canonical_headers = '';
        foreach ($headers as $k => $v) {
            $canonical_headers .= $k . ':' . trim($v) . "\n";
        }
        $signed_headers = implode(';', array_keys($headers));

        $canonical_request = "PUT\n" .
                             $request_uri . "\n" .
                             "" . "\n" .
                             $canonical_headers . "\n" .
                             $signed_headers . "\n" .
                             $payload_hash;

        $algorithm = 'AWS4-HMAC-SHA256';
        $credential_scope = $date . '/' . $region . '/s3/aws4_request';
        $string_to_sign = $algorithm . "\n" .
                          $timestamp . "\n" .
                          $credential_scope . "\n" .
                          hash('sha256', $canonical_request);

        // Compute signing keys
        $k_date = hash_hmac('sha256', $date, 'AWS4' . $secret_key, true);
        $k_region = hash_hmac('sha256', $region, $k_date, true);
        $k_service = hash_hmac('sha256', 's3', $k_region, true);
        $k_signing = hash_hmac('sha256', 'aws4_request', $k_service, true);

        $signature = hash_hmac('sha256', $string_to_sign, $k_signing);
        $authorization = "$algorithm Credential=$access_key/$credential_scope, SignedHeaders=$signed_headers, Signature=$signature";

        // Assemble request arguments
        $args = array(
            'method'    => 'PUT',
            'headers'   => array(
                'Content-Type'         => 'application/octet-stream',
                'Host'                 => $host,
                'x-amz-content-sha256' => $payload_hash,
                'x-amz-date'           => $timestamp,
                'Authorization'        => $authorization
            ),
            'body'      => $file_content,
            'timeout'   => 600, // Generous timeout for large archive streams
            'sslverify' => false
        );

        $response = wp_remote_request($request_url, $args);
        if (is_wp_error($response)) {
            throw new Exception("S3 Transmission Error: " . $response->get_error_message());
        }

        $status_code = wp_remote_retrieve_response_code($response);
        if ($status_code < 200 || $status_code >= 300) {
            $response_body = wp_remote_retrieve_body($response);
            throw new Exception("S3 API rejection. Status: {$status_code}. Response: {$response_body}");
        }

        return true;
    }

    /**
     * Recursively delete folder and files
     */
    private function recursive_cleanup($dir) {
        if (!file_exists($dir)) {
            return;
        }

        $files = array_diff(scandir($dir), array('.', '..'));
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            if (is_dir($path)) {
                $this->recursive_cleanup($path);
            } else {
                unlink($path);
            }
        }
        rmdir($dir);
    }
}

// Instantiate core plugin controller
new WPCentral_Worker_Controller();
