<?php
/**
 * Plugin Name: WP Central Worker Plugin
 * Description: Lightweight WordPress worker plugin for Central WordPress Management System. Supports secure HMAC-SHA256 authentication, asynchronous backups (to S3 or local disk), automated updates, and custom plugin vault sideloading.
 * Version: 1.2.3
 * Author: WP Central Team
 * License: GPL2
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

/**
 * Security & Authentication Helper Class
 */
class WPCentral_Security {
    private static $secret_key_option_name = 'wp_central_secret_key';

    public static function get_secret_key() {
        $secret = get_option(self::$secret_key_option_name);
        if (!$secret) {
            $secret = defined('WP_CENTRAL_SECRET_KEY') ? WP_CENTRAL_SECRET_KEY : 'default_secret_key_12345';
        }
        return $secret;
    }

    public static function set_secret_key($key) {
        update_option(self::$secret_key_option_name, $key);
    }

    /**
     * Reconstruct and verify the HMAC-SHA256 signature
     */
    public static function verify_request(WP_REST_Request $request) {
        $signature = $request->get_header('X-Signature');
        $timestamp = intval($request->get_header('X-Timestamp'));

        if (empty($signature) || empty($timestamp)) {
            return new WP_Error(
                'rest_forbidden',
                __('Missing signature or timestamp headers.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 1. Prevent Replay: Check clock drift (max 5 minutes)
        if (abs(time() - $timestamp) > 300) {
            return new WP_Error(
                'rest_forbidden',
                __('Request expired. Clock drift too high.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 2. Prevent Replay: Verify signature hasn't been used before
        $transient_key = 'wp_central_sig_' . md5($signature);
        if (get_transient($transient_key)) {
            return new WP_Error(
                'rest_forbidden',
                __('Replay attack detected. Signature already used.', 'wp-central'),
                array('status' => 401)
            );
        }

        // 3. Verify Signature
        $raw_body = $request->get_body();
        $data_to_sign = $timestamp . '.' . $raw_body;
        $secret_key = self::get_secret_key();
        $expected_signature = hash_hmac('sha256', $data_to_sign, $secret_key);

        if (!hash_equals($expected_signature, $signature)) {
            return new WP_Error(
                'rest_forbidden',
                __('Invalid signature.', 'wp-central'),
                array('status' => 403)
            );
        }

        // Store the signature in transient to prevent replay for the duration of its validity (5 minutes)
        set_transient($transient_key, true, 300);
        return true;
    }

    /**
     * Sign requests generated by the plugin itself (for secure internal loopback requests)
     */
    public static function sign_request($body) {
        $timestamp = time();
        $secret_key = self::get_secret_key();
        $data_to_sign = $timestamp . '.' . $body;
        $signature = hash_hmac('sha256', $data_to_sign, $secret_key);
        return array(
            'X-Timestamp' => (string)$timestamp,
            'X-Signature' => $signature
        );
    }
}

/**
 * Main Worker Plugin REST Controller Class
 */
class WPCentral_Worker_Controller {

    public function __construct() {
        add_action('rest_api_init', array($this, 'register_routes'));
    }

    /**
     * Register REST API routes under the wp-central/v1 namespace
     */
    public function register_routes() {
        register_rest_route('wp-central/v1', '/backup', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_backup_initiation'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/backup-process', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_background_backup_process'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/update', array(
            'methods'             => WP_REST_Server::CREATABLE,
            'callback'            => array($this, 'handle_updates'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/job-status', array(
            'methods'             => WP_REST_Server::READABLE,
            'callback'            => array($this, 'get_job_status'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));

        register_rest_route('wp-central/v1', '/status', array(
            'methods'             => WP_REST_Server::READABLE,
            'callback'            => array($this, 'get_wp_status'),
            'permission_callback' => array('WPCentral_Security', 'verify_request')
        ));
    }

    /**
     * Return WordPress status, version, and pending updates count
     * GET /wp-json/wp-central/v1/status
     */
    public function get_wp_status(WP_REST_Request $request) {
        require_once ABSPATH . 'wp-admin/includes/update.php';
        $core_updates = get_core_updates();
        $pending_core = 0;
        if (!empty($core_updates) && isset($core_updates[0]->response) && $core_updates[0]->response === 'upgrade') {
            $pending_core = 1;
        }

        require_once ABSPATH . 'wp-admin/includes/plugin.php';
        $plugin_updates = get_plugin_updates();
        $pending_plugins = count($plugin_updates);

        return new WP_REST_Response(array(
            'status'          => 'ok',
            'wp_version'      => get_bloginfo('version'),
            'pending_core'    => $pending_core,
            'pending_plugins' => $pending_plugins,
            'total_updates'   => $pending_core + $pending_plugins
        ), 200);
    }

    /**
     * Initiates non-blocking background backup (supports Local and S3 destinations)
     * POST /wp-json/wp-central/v1/backup
     */
    public function handle_backup_initiation(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $destination = isset($params['backup_destination']) ? sanitize_text_field($params['backup_destination']) : 's3';
        $s3_config = array();

        // Validate S3 inputs only if destination is set to cloud S3
        if ($destination === 's3') {
            $required = array('s3_bucket', 's3_endpoint', 's3_region', 's3_access_key', 's3_secret_key');
            foreach ($required as $field) {
                if (empty($params[$field])) {
                    return new WP_Error(
                        'missing_parameter',
                        sprintf(__('The parameter "%s" is required for S3 backup.', 'wp-central'), $field),
                        array('status' => 400)
                    );
                }
            }
            $s3_config = array(
                'bucket'     => sanitize_text_field($params['s3_bucket']),
                'endpoint'   => esc_url_raw($params['s3_endpoint']),
                'region'     => sanitize_text_field($params['s3_region']),
                'access_key' => sanitize_text_field($params['s3_access_key']),
                'secret_key' => sanitize_text_field($params['s3_secret_key'])
            );
        }

        // Generate unique Job ID
        $job_id = 'job_backup_' . time() . '_' . wp_generate_password(8, false);

        // Store Job State and configuration securely in options
        $job_data = array(
            'status'             => 'pending',
            'type'               => 'backup',
            'backup_destination' => $destination,
            'progress'           => 0,
            'created_at'         => time(),
            's3_config'          => $s3_config
        );
        update_option('wp_central_job_' . $job_id, $job_data);

        $body = json_encode(array('job_id' => $job_id));
        $loopback_url = get_rest_url(null, '/wp-central/v1/backup-process');
        $parsed = parse_url($loopback_url);
        $host = isset($parsed['host']) ? $parsed['host'] : 'localhost';
        $port = isset($parsed['port']) ? $parsed['port'] : (isset($_SERVER['SERVER_PORT']) ? $_SERVER['SERVER_PORT'] : '80');

        // Path A: Internal Loopback URL
        $internal_url_a = 'http://127.0.0.1' . ($port ? ':' . $port : '') . (isset($parsed['path']) ? $parsed['path'] : '');
        if (isset($parsed['query'])) {
            $internal_url_a .= '?' . $parsed['query'];
        }

        // Dispatch Path A with a unique HMAC signature
        $headers_a = WPCentral_Security::sign_request($body);
        $headers_a['Content-Type'] = 'application/json';
        $headers_a['Host'] = $host;

        wp_remote_post($internal_url_a, array(
            'blocking'  => false,
            'sslverify' => false,
            'timeout'   => 0.1,
            'headers'   => $headers_a,
            'body'      => $body
        ));

        // Dispatch Path B (Public Endpoint) with its own fresh HMAC signature
        $headers_b = WPCentral_Security::sign_request($body);
        $headers_b['Content-Type'] = 'application/json';

        wp_remote_post($loopback_url, array(
            'blocking'  => false,
            'sslverify' => false,
            'timeout'   => 0.1,
            'headers'   => $headers_b,
            'body'      => $body
        ));

        // Return 202 Accepted instantly
        return new WP_REST_Response(array(
            'status' => 'accepted',
            'job_id' => $job_id
        ), 202);
    }

    /**
     * Executes the background backup process recursively
     * POST /wp-json/wp-central/v1/backup-process
     */
    public function handle_background_backup_process(WP_REST_Request $request) {
        $params = $request->get_json_params();
        $job_id = sanitize_text_field($params['job_id']);
        $this->run_backup_process_inline($job_id);
        return new WP_REST_Response(array('status' => 'finished'), 200);
    }

    /**
     * Core backup runner logic
     */
    private function run_backup_process_inline($job_id) {
        $job_data = get_option('wp_central_job_' . $job_id);
        if (!$job_data || ($job_data['status'] !== 'pending' && $job_data['status'] !== 'processing')) {
            return false;
        }

        set_time_limit(0);
        if (function_exists('ignore_user_abort')) {
            ignore_user_abort(true);
        }

        set_error_handler(function($severity, $message, $file, $line) {
            if (!(error_reporting() & $severity)) {
                return;
            }
            throw new ErrorException($message, 0, $severity, $file, $line);
        });

        $job_data['status'] = 'processing';
        $job_data['progress'] = 10;
        update_option('wp_central_job_' . $job_id, $job_data);

        $temp_dir = WP_CONTENT_DIR . '/uploads/wp-central-temp-' . $job_id;
        $sql_filepath = $temp_dir . '/db_backup.sql';
        $zip_filepath = $temp_dir . '/wp_content_backup.zip';
        $destination = isset($job_data['backup_destination']) ? $job_data['backup_destination'] : 's3';

        try {
            if (!file_exists($temp_dir)) {
                if (!mkdir($temp_dir, 0755, true)) {
                    throw new Exception("Failed to create temporary folder at: " . $temp_dir);
                }
            }

            // Step 1: Database Export
            $this->export_database($sql_filepath);
            $job_data['progress'] = 40;
            update_option('wp_central_job_' . $job_id, $job_data);

            // Step 2: Zip /wp-content/ directory
            $this->zip_wp_content($zip_filepath, $sql_filepath, $temp_dir);
            $job_data['progress'] = 70;
            update_option('wp_central_job_' . $job_id, $job_data);

            if ($destination === 's3') {
                // Step 3: Upload to S3
                $this->upload_to_s3_compatible($zip_filepath, $job_data['s3_config']);
                $this->recursive_cleanup($temp_dir);
                $final_path = 'S3 Cloud Storage Bucket: ' . $job_data['s3_config']['bucket'];
            } else {
                // Local Vault destination
                $local_vault = WP_CONTENT_DIR . '/uploads/wp-central-backups';
                if (!file_exists($local_vault)) {
                    if (!mkdir($local_vault, 0755, true)) {
                        throw new Exception("Failed to create local backups directory: " . $local_vault);
                    }
                }
                $local_archive_name = 'backup_' . $job_id . '.zip';
                $final_archive_path = $local_vault . '/' . $local_archive_name;

                if (!rename($zip_filepath, $final_archive_path)) {
                    throw new Exception("Failed to save zip to local backups folder.");
                }

                $this->recursive_cleanup($temp_dir);
                $final_path = $final_archive_path;
            }

            $job_data['status'] = 'completed';
            $job_data['progress'] = 100;
            $job_data['completed_at'] = time();
            $job_data['archive_name'] = basename($zip_filepath);
            $job_data['local_backup_path'] = $final_path;
            unset($job_data['s3_config']);
            update_option('wp_central_job_' . $job_id, $job_data);
            return true;
        } catch (Throwable $e) {
            $this->recursive_cleanup($temp_dir);
            $formatted_error = sprintf(
                "PHP Exception: %s inside file %s at line %d",
                $e->getMessage(),
                basename($e->getFile()),
                $e->getLine()
            );
            $job_data['status'] = 'failed';
            $job_data['error'] = $formatted_error;
            unset($job_data['s3_config']);
            update_option('wp_central_job_' . $job_id, $job_data);
            return false;
        } finally {
            restore_error_handler();
        }
    }

    /**
     * Core & Plugins Update Orchestrator
     * POST /wp-json/wp-central/v1/update
     */
    public function handle_updates(WP_REST_Request $request) {
    // 1. Force higher limits for this thread
    @ini_set('memory_limit', '512M');
    @set_time_limit(300);

    // 2. Register shutdown function to catch silent fatal crashes
    register_shutdown_function(function() {
        $error = error_get_last();
        if ($error && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
            if (ob_get_length()) {
                ob_end_clean();
            }
            header('Content-Type: application/json', true, 500);
            echo json_encode([
                'status'  => 'error',
                'message' => sprintf('Fatal PHP Error: %s in %s on line %d', $error['message'], basename($error['file']), $error['line'])
            ]);
            exit;
        }
    });

    $params = $request->get_json_params();
    $type = sanitize_text_field($params['type']);

    try {
        $admin_users = get_users(['role' => 'Administrator']);
        $admin_id = (!empty($admin_users)) ? $admin_users[0]->ID : 1;
        wp_set_current_user($admin_id);

        if (!defined('WP_ADMIN')) {
            define('WP_ADMIN', true);
        }

        add_filter('filesystem_method', function() { return 'direct'; }, 9999);

        // Load WordPress Upgrader Dependencies explicitly
        require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
        require_once ABSPATH . 'wp-admin/includes/class-automatic-upgrader-skin.php';
        require_once ABSPATH . 'wp-admin/includes/file.php';
        require_once ABSPATH . 'wp-admin/includes/plugin.php';
        require_once ABSPATH . 'wp-admin/includes/theme.php';
        require_once ABSPATH . 'wp-admin/includes/admin.php';
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        require_once ABSPATH . 'wp-admin/includes/plugin-install.php';
        require_once ABSPATH . 'wp-admin/includes/update.php';

        global $wp_filesystem;
        if (empty($wp_filesystem)) {
            ob_start();
            $creds = request_filesystem_credentials('', '', false, false, null);
            ob_end_clean();
            if (!WP_Filesystem($creds)) {
                if (!defined('FS_METHOD')) {
                    define('FS_METHOD', 'direct');
                }
                WP_Filesystem();
            }
        }

        if ($type === 'core') {
            wp_version_check();
            $updates = get_core_updates();

            if (empty($updates) || !isset($updates[0]->response) || $updates[0]->response !== 'upgrade') {
                return new WP_REST_Response([
                    'status'  => 'success',
                    'message' => 'WordPress Core is already up to date.'
                ], 200);
            }

            $upgrader = new Core_Upgrader(new Automatic_Upgrader_Skin());
            $result = $upgrader->upgrade($updates[0]);

            if (is_wp_error($result)) {
                return new WP_REST_Response([
                    'status'  => 'error',
                    'message' => 'Upgrader Error: ' . $result->get_error_message()
                ], 500);
            }

            return new WP_REST_Response([
                'status'  => 'success',
                'message' => 'WordPress Core updated successfully.'
            ], 200);

        } elseif ($type === 'plugin') {
            $plugins = $params['plugins'];
            if (empty($plugins) || !is_array($plugins)) {
                return new WP_REST_Response([
                    'status'  => 'error',
                    'message' => 'A valid list of plugins must be provided.'
                ], 400);
            }

            wp_update_plugins();
            $standard_upgrades = [];
            $custom_upgrades_results = [];
            $upgrader = new Plugin_Upgrader(new Automatic_Upgrader_Skin());

            foreach ($plugins as $plugin_item) {
                $plugin_file = is_string($plugin_item) ? sanitize_text_field($plugin_item) : (isset($plugin_item['file']) ? sanitize_text_field($plugin_item['file']) : '');
                $package_url = is_array($plugin_item) && isset($plugin_item['package_url']) ? esc_url_raw($plugin_item['package_url']) : '';

                if (empty($plugin_file)) continue;

                if (!empty($package_url)) {
                    $download_result = download_url($package_url);
                    if (is_wp_error($download_result)) {
                        $custom_upgrades_results[$plugin_file] = [
                            'status'  => 'error',
                            'message' => 'Download failed: ' . $download_result->get_error_message()
                        ];
                        continue;
                    }

                    $install_result = $upgrader->install($download_result, ['overwrite_package' => true]);

                    if (file_exists($download_result)) {
                        @unlink($download_result);
                    }

                    $custom_upgrades_results[$plugin_file] = is_wp_error($install_result) ? [
                        'status'  => 'error',
                        'message' => $install_result->get_error_message()
                    ] : [
                        'status'  => 'success',
                        'message' => 'Plugin updated successfully.'
                    ];
                } else {
                    $standard_upgrades[] = $plugin_file;
                }
            }

            $standard_results = null;
            if (!empty($standard_upgrades)) {
                $standard_results = $upgrader->bulk_upgrade($standard_upgrades);
            }

            wp_clean_plugins_cache(true);
            delete_site_transient('update_plugins');

            return new WP_REST_Response([
                'status'           => 'success',
                'message'          => 'Plugins update operation completed.',
                'custom_results'   => $custom_upgrades_results,
                'standard_results' => $standard_results
            ], 200);
        }

        return new WP_REST_Response(['status' => 'error', 'message' => 'Invalid update type.'], 400);

    } catch (Throwable $e) {
        return new WP_REST_Response([
            'status'  => 'error',
            'message' => sprintf('Exception: %s inside %s:%d', $e->getMessage(), basename($e->getFile()), $e->getLine())
        ], 500);
    }
}

    /**
     * Poll status endpoint for asynchronous jobs
     * GET /wp-json/wp-central/v1/job-status
     */
    public function get_job_status(WP_REST_Request $request) {
        $job_id = sanitize_text_field($request->get_param('job_id'));
        if (empty($job_id)) {
            return new WP_Error(
                'missing_job_id',
                __('Missing job_id parameter.', 'wp-central'),
                array('status' => 400)
            );
        }

        $job_data = get_option('wp_central_job_' . $job_id);
        if (!$job_data) {
            return new WP_Error(
                'job_not_found',
                __('The specified background job was not found.', 'wp-central'),
                array('status' => 404)
            );
        }

        if ($job_data['status'] === 'pending' && (time() - intval($job_data['created_at'])) > 5) {
            $this->run_backup_process_inline($job_id);
            $job_data = get_option('wp_central_job_' . $job_id);
        }

        return new WP_REST_Response($job_data, 200);
    }

    /**
     * Database Dumper
     */
   private function export_database($filepath) {
    global $wpdb;
    $tables = $wpdb->get_col("SHOW TABLES");
    $handle = fopen($filepath, 'w');
    if (!$handle) {
        throw new Exception("Unable to open SQL file for writing at: " . $filepath);
    }

    fwrite($handle, "-- WP Central Database Backup\n-- Date: " . date('Y-m-d H:i:s') . "\n\n");

    foreach ($tables as $table) {
        $create_table = $wpdb->get_row("SHOW CREATE TABLE `$table`", ARRAY_N);
        fwrite($handle, "DROP TABLE IF EXISTS `$table`;\n" . $create_table[1] . ";\n\n");

        $count = $wpdb->get_var("SELECT COUNT(*) FROM `$table`");
        $chunk_size = 500;

        for ($offset = 0; $offset < $count; $offset += $chunk_size) {
            $rows = $wpdb->get_results("SELECT * FROM `$table` LIMIT $chunk_size OFFSET $offset", ARRAY_A);
            foreach ($rows as $row) {
                $escaped_values = array_map(function($val) {
                    return is_null($val) ? 'NULL' : "'" . esc_sql($val) . "'";
                }, array_values($row));
                
                $keys = array_map(function($k) { return "`$k`"; }, array_keys($row));
                fwrite($handle, "INSERT INTO `$table` (" . implode(', ', $keys) . ") VALUES (" . implode(', ', $escaped_values) . ");\n");
            }
        }
        fwrite($handle, "\n\n");
    }
    fclose($handle);
}

    /**
     * Zip recursive worker excluding workspace directory
     */
    private function zip_wp_content($zip_filepath, $sql_filepath, $exclude_dir) {
    if (!class_exists('ZipArchive')) {
        throw new Exception("ZipArchive PHP extension is not installed on this server.");
    }

    $zip = new ZipArchive();
    if ($zip->open($zip_filepath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
        throw new Exception("Could not create ZIP archive at: " . $zip_filepath);
    }

    $wp_content_dir = wp_normalize_path(rtrim(WP_CONTENT_DIR, '/\\'));
    $norm_exclude_dir = wp_normalize_path($exclude_dir);
    $norm_backups_dir = wp_normalize_path(WP_CONTENT_DIR . '/uploads/wp-central-backups');

    $files = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($wp_content_dir, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::LEAVES_ONLY
    );

    foreach ($files as $file) {
        if (!$file->isDir()) {
            $real_path = wp_normalize_path($file->getRealPath());

            // Skip current temp directory and local backup vault
            if ($real_path && (strpos($real_path, $norm_exclude_dir) === 0 || strpos($real_path, $norm_backups_dir) === 0)) {
                continue;
            }

            if (!is_readable($real_path)) {
                continue;
            }

            $relative_path = substr($real_path, strlen($wp_content_dir) + 1);
            $zip->addFile($real_path, 'wp-content/' . $relative_path);
        }
    }

    $zip->addFile($sql_filepath, 'database_dump.sql');
    $zip->close();
}

    /**
     * AWS Signature V4 S3 client
     */
    private function upload_to_s3_compatible($filepath, $s3_config) {
        $bucket = $s3_config['bucket'];
        $endpoint = rtrim($s3_config['endpoint'], '/');
        $region = $s3_config['region'];
        $access_key = $s3_config['access_key'];
        $secret_key = $s3_config['secret_key'];
        $object_name = basename($filepath);

        $file_content = file_get_contents($filepath);
        if ($file_content === false) {
            throw new Exception("Unable to read backup zip archive for upload.");
        }

        $payload_hash = hash('sha256', $file_content);
        $host = parse_url($endpoint, PHP_URL_HOST);
        $timestamp = gmdate('Ymd\THis\Z');
        $date = substr($timestamp, 0, 8);

        $request_uri = '/' . $bucket . '/' . $object_name;
        $request_url = $endpoint . '/' . $bucket . '/' . $object_name;

        $headers = array(
            'content-type'         => 'application/octet-stream',
            'host'                 => $host,
            'x-amz-content-sha256' => $payload_hash,
            'x-amz-date'           => $timestamp,
        );

        ksort($headers);
        $canonical_headers = '';
        foreach ($headers as $k => $v) {
            $canonical_headers .= $k . ':' . trim($v) . "\n";
        }

        $signed_headers = implode(';', array_keys($headers));
        $canonical_request = "PUT\n" .
                             $request_uri . "\n" .
                             "" . "\n" .
                             $canonical_headers . "\n" .
                             $signed_headers . "\n" .
                             $payload_hash;

        $algorithm = 'AWS4-HMAC-SHA256';
        $credential_scope = $date . '/' . $region . '/s3/aws4_request';
        $string_to_sign = $algorithm . "\n" .
                          $timestamp . "\n" .
                          $credential_scope . "\n" .
                          hash('sha256', $canonical_request);

        $k_date = hash_hmac('sha256', $date, 'AWS4' . $secret_key, true);
        $k_region = hash_hmac('sha256', $region, $k_date, true);
        $k_service = hash_hmac('sha256', 's3', $k_region, true);
        $k_signing = hash_hmac('sha256', 'aws4_request', $k_service, true);
        $signature = hash_hmac('sha256', $string_to_sign, $k_signing);

        $authorization = "$algorithm Credential=$access_key/$credential_scope, SignedHeaders=$signed_headers, Signature=$signature";

        $args = array(
            'method'    => 'PUT',
            'headers'   => array(
                'Content-Type'         => 'application/octet-stream',
                'Host'                 => $host,
                'x-amz-content-sha256' => $payload_hash,
                'x-amz-date'           => $timestamp,
                'Authorization'        => $authorization
            ),
            'body'      => $file_content,
            'timeout'   => 600,
            'sslverify' => false
        );

        $response = wp_remote_request($request_url, $args);

        if (is_wp_error($response)) {
            throw new Exception("S3 Transmission Error: " . $response->get_error_message());
        }

        $status_code = wp_remote_retrieve_response_code($response);
        if ($status_code < 200 || $status_code >= 300) {
            $response_body = wp_remote_retrieve_body($response);
            throw new Exception("S3 API rejection. Status: {$status_code}. Response: {$response_body}");
        }

        return true;
    }

    private function recursive_cleanup($dir) {
        if (!file_exists($dir)) {
            return;
        }
        $files = array_diff(scandir($dir), array('.', '..'));
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            if (is_dir($path)) {
                $this->recursive_cleanup($path);
            } else {
                unlink($path);
            }
        }
        rmdir($dir);
    }
}

new WPCentral_Worker_Controller();